//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MessageCore.Infrastructure.Exceptions {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ErrorMessage {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ErrorMessage() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MessageCore.Infrastructure.Exceptions.ErrorMessage", typeof(ErrorMessage).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 数据验证失败：{0} 的本地化字符串。
        /// </summary>
        public static string CommandValidateError {
            get {
                return ResourceManager.GetString("CommandValidateError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 找不到邮件服务！ 的本地化字符串。
        /// </summary>
        public static string EmailServiceNotFound {
            get {
                return ResourceManager.GetString("EmailServiceNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 找不到企业微信服务！ 的本地化字符串。
        /// </summary>
        public static string EnterpriseWeChatServiceNotFound {
            get {
                return ResourceManager.GetString("EnterpriseWeChatServiceNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 获取用户信息失败：{0} 的本地化字符串。
        /// </summary>
        public static string GetUserInfoError {
            get {
                return ResourceManager.GetString("GetUserInfoError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 找不到发起人信息：{0} 的本地化字符串。
        /// </summary>
        public static string IssuerNotFoundError {
            get {
                return ResourceManager.GetString("IssuerNotFoundError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户：{0}，登录失败！{1} 的本地化字符串。
        /// </summary>
        public static string LoginFail {
            get {
                return ResourceManager.GetString("LoginFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 登出失败！{1} 的本地化字符串。
        /// </summary>
        public static string LogoutFail {
            get {
                return ResourceManager.GetString("LogoutFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 找不到消息拦截数据：{0} 的本地化字符串。
        /// </summary>
        public static string MessageBlockingNotFoundError {
            get {
                return ResourceManager.GetString("MessageBlockingNotFoundError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 找不到消息服务：{0} 的本地化字符串。
        /// </summary>
        public static string MessageSendingServiceNotFoundError {
            get {
                return ResourceManager.GetString("MessageSendingServiceNotFoundError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 消息服务{0}未开启 的本地化字符串。
        /// </summary>
        public static string SendingServiceEnabledError {
            get {
                return ResourceManager.GetString("SendingServiceEnabledError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 发送信息服务类型错误！ 的本地化字符串。
        /// </summary>
        public static string SendingServiceTypeError {
            get {
                return ResourceManager.GetString("SendingServiceTypeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 发送企业微信失败：{0} 的本地化字符串。
        /// </summary>
        public static string SimpleEnterpriseWeChatServiceError {
            get {
                return ResourceManager.GetString("SimpleEnterpriseWeChatServiceError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 找不到短信服务！ 的本地化字符串。
        /// </summary>
        public static string SmsServiceNotFound {
            get {
                return ResourceManager.GetString("SmsServiceNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 找不到模板信息：{0} 的本地化字符串。
        /// </summary>
        public static string TemplateNotFoundError {
            get {
                return ResourceManager.GetString("TemplateNotFoundError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 系统出现未处理异常：{0} 的本地化字符串。
        /// </summary>
        public static string UnhandledError {
            get {
                return ResourceManager.GetString("UnhandledError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 数据验证失败：{0} 的本地化字符串。
        /// </summary>
        public static string ValidateError {
            get {
                return ResourceManager.GetString("ValidateError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 登陆失败：{0} 的本地化字符串。
        /// </summary>
        public static string ValidateTokenError {
            get {
                return ResourceManager.GetString("ValidateTokenError", resourceCulture);
            }
        }
    }
}
